// Type declarations for static image imports (`import x from "./foo.webp"`),
// which resolve to a Next.js `StaticImageData`.
//
// Next normally provides these via `next-env.d.ts`, but that file is gitignored
// and only generated by a `next` command — and CI runs `tsc` *before*
// `next build`, so static image imports would otherwise fail type-checking.
// Referencing Next's own declarations here (rather than redeclaring the modules)
// keeps it working in CI without conflicting with `next-env.d.ts` locally.
/// <reference types="next/image-types/global" />
