-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'FEED_ITEM_LIKED';
ALTER TYPE "NotificationType" ADD VALUE 'FEED_ITEM_COMMENTED';
ALTER TYPE "NotificationType" ADD VALUE 'FEED_ITEM_COMMENT_REPLY';
