name: Code Coverage

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: volunteer-portal
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Setup test database
        run: |
          cp .env.example .env
          echo "NEXTAUTH_SECRET=test-secret-for-ci" >> .env.local
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.local
          npx prisma migrate deploy
          npx prisma db seed

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/volunteer-portal
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-for-ci

      - name: Run Playwright tests
        run: npx playwright test --project=chromium --reporter=html,json
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/volunteer-portal
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-for-ci

      - name: Parse test results for coverage info
        run: |
          # Extract test results and create a simple coverage report
          echo "# Test Coverage Report" > coverage-report.md
          echo "" >> coverage-report.md
          
          # Count test files and results
          TEST_COUNT=$(find tests/e2e -name "*.spec.ts" -o -name "*.test.ts" | wc -l)
          echo "- **Total test files**: $TEST_COUNT" >> coverage-report.md
          
          # Check if test results exist
          if [ -f "test-results.json" ]; then
            echo "- **Test results**: Available in JSON format" >> coverage-report.md
          else
            echo "- **Test results**: Not available" >> coverage-report.md
          fi
          
          # List test files covered
          echo "" >> coverage-report.md
          echo "## Test Files Executed" >> coverage-report.md
          find tests/e2e -name "*.spec.ts" -o -name "*.test.ts" | while read file; do
            echo "- \`$(basename $file)\`" >> coverage-report.md
          done
          
          echo "" >> coverage-report.md
          echo "## Pages/Components Tested" >> coverage-report.md
          echo "Based on e2e tests, the following application areas are covered:" >> coverage-report.md
          
          # Analyze test files for page coverage
          grep -r "page\.goto\|visit" tests/e2e/ --include="*.ts" | \
            sed 's/.*page\.goto[^"]*["'"'"']\([^"'"'"']*\)["'"'"'].*/- \1/' | \
            sort | uniq >> coverage-report.md || echo "- No specific page visits found" >> coverage-report.md

      - name: Comment PR with test coverage info
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let coverageReport = '';
            try {
              coverageReport = fs.readFileSync('web/coverage-report.md', 'utf8');
            } catch (error) {
              coverageReport = '# Test Coverage Report\n\nNo coverage report generated.';
            }
            
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            // Find existing coverage comment
            const existingComment = comments.find(comment => 
              comment.body.includes('Test Coverage Report') && 
              comment.user.type === 'Bot'
            );
            
            const commentBody = `## 🧪 Test Coverage Report
            
            ${coverageReport}
            
            ---
            *This report shows which test files were executed and provides insight into application coverage through e2e tests.*`;
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }